### PR TITLE
Kittens create form and screenshots

### PR DESCRIPTION
**Pull request by kgish**
Additional functionality for creating kittens and readme updates to explain how to implement this.

### CODE REVIEW

**Comment by oliverguenther** [comment]
Could you rebase this on the current `dev` branch of this plugin (or merge dev into it)? It contains a fix that solves the first spec failure.

**Comment by lindenthal** [comment]
@kgish What is this PR about? Can you please a short description?

**Comment by kgish** [comment]
@oliverguenther : assuming that you mean the `master` branch.

**Comment by kgish** [comment]
Tried running `git pull --rebase upstream dev` but was unable to fix readme conflicts.

**Comment by oliverguenther** [comment]
Seems to work fine with the last commit of yours since the reference to the plugins matrix entry on travis is fixed. The one failing feature is not connected to your PR.

**Pull request merged**
